#!/usr/bin/env node

// Dependencies
var fs = require("fs"),
    uglifyJS = require("uglify-js"),
    sass = require('node-sass'),
    cleanCSS = require('clean-css');

// Constants
var embedButtonSrc = fs.readFileSync("./src/js/medium-editor-embed-button.js", "utf-8"),
    embedSassSrc = fs.readFileSync("./src/scss/medium-editor-embed-button.scss", "utf-8");

var sassResult = sass.renderSync({
            data: embedSassSrc
        }).css,
    minifiedCss = new cleanCSS().minify(sassResult).styles;

// Create the dist files
fs.writeFileSync("./dist/js/medium-editor-embed-button.js", embedButtonSrc);
fs.writeFileSync("./dist/js/medium-editor-embed-button.min.js", uglifyJS.minify(embedButtonSrc, { fromString: true }).code);
fs.writeFileSync("./dist/css/medium-editor-embed-button.css", sassResult);
fs.writeFileSync("./dist/css/medium-editor-embed-button.min.css", minifiedCss);
